brew reinstall bash 
brew reinstall bash-completion 
brew reinstall bib-tool 
brew reinstall brew-cask 
brew reinstall cmus 
brew reinstall coreutils 
brew reinstall cscope 
brew reinstall fftw 
brew reinstall findutils 
brew reinstall gdbm 
brew reinstall gfortran 
brew reinstall gifsicle 
brew reinstall git 
brew reinstall grep 
brew reinstall hdf5 
brew reinstall hub 
brew reinstall icu4c 
brew reinstall imagemagick 
brew reinstall intltool 
brew reinstall libiconv 
brew reinstall libidn 
brew reinstall make 
brew reinstall matplotlib --with-tex 
brew reinstall mercurial 
brew reinstall mpg123 
brew reinstall ncftp 
brew reinstall opencv 
brew reinstall pygame 
brew reinstall rsync 
brew reinstall scipy 
brew reinstall screen 
brew reinstall smpeg 
brew reinstall sqlite 
brew reinstall suite-sparse 
brew reinstall tcl-tk 
brew reinstall unison 
brew reinstall vim 
brew reinstall wget --enable-iri 
brew reinstall zeromq 
